### ISSUE TITLE
Option to generate copyWith method

### ISSUE THREAD

**Issue by Sumit258000** [windows7lake/json2dart#2]
Thanks for wonderfull plugin. It would be awesome if it have `copyWith `method.

**Comment by windows7lake** [comment]
@Sumit258000 Thanks for your support! pls upgrade to v1.2.1. it is under review, and will update about two day later.

**Comment by Sumit258000** [comment]
Still didn't find any [updates ](https://plugins.jetbrains.com/plugin/14921-json2dart-safe-convert)in Android Studio.

**Comment by Sumit258000** [comment]
Is there a way I can install manually? I tried downloading from releases but it gives error `
Fail to load plugin descriptor from file json2dart-1.2.1.zip` @windows7lake

**Comment by windows7lake** [comment]
@Sumit258000 I'm sorry for that Jetbrain Plugin Store still block the release package. You can download version 1.2.1 form this link. https://github.com/windows7lake/json2dart/releases/tag/1.2.1

**Comment by Sumit258000** [comment]
It still gives the same error `Fail to load plugin descriptor from file json2dart-1.2.1.zip` please refer to the [screenshot](https://drive.google.com/file/d/16owz2lxnj89ZWcrHnXM2nH9KojIU39ar/view?usp=sharing).

**Comment by windows7lake** [comment]
@Sumit258000 Which version of your Android Studio that you are using?

**Comment by windows7lake** [comment]
[json2dart-1.2.0.zip](https://github.com/windows7lake/json2dart/files/12839524/json2dart-1.2.0.zip)
@windows7lake try this package

**Comment by Sumit258000** [comment]
Wow!! Works like a dream!!!. Thank you so much for brilliant work. God bless you.
